#!/bin/bash
# Temporary workaround until rebuild completes

echo "=== Quick Workaround (until rebuild) ==="
echo ""
echo "The 'python' command is missing. Use 'python3' instead:"
echo ""
echo "Terminal 3 - ArduPilot:"
echo "  docker exec -it ap_nongps_container bash"
echo "  cd /root/ardupilot"
echo "  python3 Tools/autotest/sim_vehicle.py -D -v ArduCopter -f JSON --add-param-file=/root/ardupilot_gazebo_ap/config/gazebo-iris-gimbal-ngps.parm --console --map"
echo ""
echo "Terminal 4 - State Estimator:"
echo "  docker exec -it ap_nongps_container bash"
echo "  cd /root/ap_nongps/src"
echo "  python3 video_to_feature.py"
echo ""
echo "=== Permanent Fix ==="
echo "Rebuild the container to add 'python' command:"
echo "  docker-compose down"
echo "  docker-compose build"
echo "  docker-compose up -d"
echo ""
